data_vi = {
    "lang": "vi",
    "site_url": "https://lanpinktattoo.netlify.app",
    "brand": "Lan Pink Tattoo",
    "slogan": "Nghệ thuật trên da, dấu ấn của riêng bạn",
    "meta_title": "Lan Pink Tattoo Q12 - Xăm Mini, Fine Line, Cover Tattoo HCM",
    "meta_desc": "Lan Pink Tattoo chuyên xăm mini, fine line, màu nước tại Quận 12. An toàn, mực USA, thiết kế riêng. Gần cầu vượt Tân Thới Hiệp. Đặt lịch: 0909 xxx xxx",
    "keywords": "xăm quận 12, tattoo mini, fine line tattoo, cover tattoo hcm, xăm hình tphcm",
    "phone": "0909 xxx xxx",
    "address": "Gần cầu vượt Tân Thới Hiệp, Quận 12, TP.HCM",
    "address_short": "Q.12, TP.HCM",
    "maps_embed": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.297687683675!2d106.64560557518416!3d10.864947757554367!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175297e1d5f90ad%3A0x6dcd055198206b25!2slanpink%20ink%20-%20Private%20Tattoo%20studio!5e0!3m2!1svi!2s!4v1780898799264!5m2!1svi!2s",
    "maps_link": "https://www.google.com/maps/dir//lanpink+ink+Private+Tattoo+studio/@10.8649477,106.6456056,17z",
    "instagram": "https://instagram.com/lanpinktattoo",
    "facebook": "https://facebook.com/lanpinktattoo",
    "og_image": "static/images/og-cover.jpg",
    "nav_services": "Dịch vụ",
    "nav_gallery": "Tác phẩm",
    "nav_contact": "Liên hệ",
    "nav_map": "Bản đồ",
    "about_title": "Về chúng tôi",
    "about": "Lan Pink Tattoo chuyên các dòng fine line, mini tattoo, màu nước. An toàn, vệ sinh, mực USA chính hãng.",
    "services_title": "Dịch vụ nổi bật",
    "services": [
        {"name": "Tattoo Mini", "desc": "Hình nhỏ tinh tế, ít đau", "price": "từ 500k"},
        {"name": "Tattoo Màu", "desc": "Lên màu chuẩn, bền theo năm tháng", "price": "từ 1tr5"},
        {"name": "Cover Tattoo", "desc": "Che sẹo, che hình cũ chuyên nghiệp", "price": "Báo giá sau tư vấn"},
        {"name": "Thiết kế riêng", "desc": "Vẽ theo ý tưởng của bạn", "price": "từ 1tr"},
    ],
    "gallery_title": "Tác phẩm",
    "gallery": [
        {"img": "images/tattoo1.jpg", "alt": "Hình xăm mini hoa tại Quận 12"},
        {"img": "images/tattoo2.jpg", "alt": "Xăm chữ fine line Lan Pink Tattoo"},
        {"img": "images/tattoo3.jpg", "alt": "Tattoo màu nước nghệ thuật HCM"},
    ],
    "map_title": "Tìm đường đến tiệm",
    "map_btn": "Mở Google Maps chỉ đường",
    "cta_title": "Đặt lịch ngay",
    "cta_btn": "Gọi",
    "footer_address": "Địa chỉ",
    "footer_phone": "SĐT",
    "other_lang": "English",
    "other_lang_link": "/en/",
    "other_lang_code": "en"
}

data_en = {
    "lang": "en",
    "site_url": "https://lanpinktattoo.netlify.app",
    "brand": "Lan Pink Tattoo",
    "slogan": "Art on skin, your personal mark",
    "meta_title": "Lan Pink Tattoo HCMC - Mini Tattoo, Fine Line, Cover-up District 12",
    "meta_desc": "Lan Pink Tattoo in District 12 HCMC. Specializing in fine line, mini tattoo, watercolor. Safe, USA ink, custom design. Near Tan Thoi Hiep Overpass. Book: 0909 xxx xxx",
    "keywords": "tattoo district 12, mini tattoo hcmc, fine line tattoo saigon, cover up tattoo",
    "phone": "0909 xxx xxx",
    "address": "Near Tan Thoi Hiep Overpass, District 12, HCMC",
    "address_short": "D.12, HCMC",
    "maps_embed": data_vi["maps_embed"],
    "maps_link": data_vi["maps_link"],
    "instagram": data_vi["instagram"],
    "facebook": data_vi["facebook"],
    "og_image": data_vi["og_image"],
    "nav_services": "Services",
    "nav_gallery": "Gallery",
    "nav_contact": "Contact",
    "nav_map": "Map",
    "about_title": "About Us",
    "about": "Lan Pink Tattoo specializes in fine line, mini tattoo, and watercolor styles. Safe, hygienic, with authentic USA ink.",
    "services_title": "Featured Services",
    "services": [
        {"name": "Mini Tattoo", "desc": "Delicate small designs, less pain", "price": "from 500k VND"},
        {"name": "Color Tattoo", "desc": "Vibrant colors, long-lasting", "price": "from 1.5M VND"},
        {"name": "Cover-up", "desc": "Professional scar & old tattoo cover", "price": "Quote after consultation"},
        {"name": "Custom Design", "desc": "Drawn from your ideas", "price": "from 1M VND"},
    ],
    "gallery_title": "Gallery",
    "gallery": [
        {"img": "images/tattoo1.jpg", "alt": "Floral mini tattoo District 12 HCMC"},
        {"img": "images/tattoo2.jpg", "alt": "Fine line lettering tattoo Lan Pink"},
        {"img": "images/tattoo3.jpg", "alt": "Watercolor tattoo art Saigon"},
    ],
    "map_title": "Find Us",
    "map_btn": "Get Directions on Google Maps",
    "cta_title": "Book Now",
    "cta_btn": "Call",
    "footer_address": "Address",
    "footer_phone": "Phone",
    "other_lang": "Tiếng Việt",
    "other_lang_link": "/",
    "other_lang_code": "vi"
}
