[build]
command = "hugo"
publish = "public"

[build.environment]
  TZ = "Asia/Ho_Chi_Minh"
HUGO_VERSION = "0.152.2"



[[redirects]]

from = "https://lanpinktattoo.netlify.app/ *"

to = "https://lanpinktattoo.com/:splat"

status = 301

force = true



[[redirects]]

from = "http://TEN-SITE-NETLIFY-CUA-ANH.netlify.app/*"

to = "https://lanpinktattoo.com/:splat"

status = 301

force = true
