content = {
    "lang": "vi",
    "meta_title": "Lan Pink Tattoo Q12 - Xăm Mini, Fine Line, Cover Tattoo HCM",
    "meta_desc": "Lan Pink Tattoo chuyên xăm mini, fine line, màu nước tại Quận 12. An toàn, mực USA, thiết kế riêng. Gần cầu vượt Tân Thới Hiệp. Đặt lịch: 0909 xxx xxx",
    "keywords": "xăm quận 12, tattoo mini, fine line tattoo, cover tattoo hcm, xăm hình tphcm",
    "nav_services": "Dịch vụ",
    "nav_gallery": "Tác phẩm",
    "nav_contact": "Liên hệ",
    "nav_map": "Bản đồ",
    "about_title": "Về chúng tôi",
    "about": "Lan Pink Tattoo chuyên các dòng fine line, mini tattoo, màu nước. An toàn, vệ sinh, mực USA chính hãng.",
    "services_title": "Dịch vụ nổi bật",
    "services": [
        {"name": "Tattoo Mini", "desc": "Hình nhỏ tinh tế, ít đau", "price": "từ 500k"},
        {"name": "Tattoo Màu", "desc": "Lên màu chuẩn, bền theo năm tháng", "price": "từ 1tr5"},
        {"name": "Cover Tattoo", "desc": "Che sẹo, che hình cũ chuyên nghiệp", "price": "Báo giá sau tư vấn"},
        {"name": "Thiết kế riêng", "desc": "Vẽ theo ý tưởng của bạn", "price": "từ 1tr"},
    ],
    "gallery_title": "Tác phẩm",
    "map_title": "Tìm đường đến tiệm",
    "map_btn": "Mở Google Maps chỉ đường",
    "cta_title": "Đặt lịch ngay",
    "cta_btn": "Gọi",
    "footer_address": "Địa chỉ",
    "footer_phone": "SĐT",
    "other_lang": "English",
    "other_lang_link": "/en/",
    "other_lang_code": "en"
}
